version: "3"

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_PORT=3306 # cannot change this port to other number
      - MYSQL_DATABASE=stocks # name you want for the database
      - MYSQL_USER=khalsa # change to whatever username you want
      - MYSQL_PASSWORD=khalsa123@KH #change to the password you want for user
      - MYSQL_ROOT_PASSWORD=khalsa123@KH #change to good root password
    ports:
      - "3305:3306"
    volumes:
      - "./db:/var/lib/mysql"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
